import type { Metadata } from "next";
import styles from "@styles/globals.module.css";
import "@components/Navbar.tsx";
import Navbar from "@components/Navbar";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.navbar}>
        <nav>
          <Navbar/>
        </nav>
      </header>
        {children}
      </body>
    </html>
  );
}
